services:
  student-db:
    image: postgres:15-alpine
    container_name: student_postgres
    environment:
      POSTGRES_USER: ${STUDENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STUDENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STUDENT_POSTGRES_DB}
    ports:
      - "${STUDENT_DB_PORT}:5432"
    volumes:
      - student_postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d

  school-db:
    image: postgres:15-alpine
    container_name: school_postgres
    environment:
      POSTGRES_USER: ${SCHOOL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SCHOOL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SCHOOL_POSTGRES_DB}
    ports:
      - "${SCHOOL_DB_PORT}:5432"
    volumes:
      - school_postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d

volumes:
  student_postgres_data:
  school_postgres_data: